# Generated by Django 5.1.6 on 2025-02-14 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_contact_options_contact_the_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
