# Generated by Django 5.1.6 on 2025-02-20 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytics',
            name='last_updated',
        ),
    ]
