# Generated by Django 5.1.6 on 2025-02-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='ip_address',
            field=models.GenericIPAddressField(primary_key=True, serialize=False),
        ),
    ]
