# Generated by Django 5.1.6 on 2025-02-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='formresponse',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='form',
        ),
        migrations.RemoveField(
            model_name='formresponse',
            name='form',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
        migrations.DeleteModel(
            name='FormResponse',
        ),
        migrations.DeleteModel(
            name='FormTemplate',
        ),
    ]
