# Generated by Django 5.1.6 on 2025-02-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_visitorinfos_options_visitorinfos_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorinfos',
            name='visit_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
