# Generated by Django 5.1.6 on 2025-02-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_analytics_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='conversion_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='analytics',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='analytics',
            name='sales_contact_visits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analytics',
            name='total_contacts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analytics',
            name='total_email_templates',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analytics',
            name='total_page_visits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analytics',
            name='total_users',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
