# Generated by Django 5.1.6 on 2025-02-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_contactmessage_remove_formresponse_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Enter the email subject.', max_length=255)),
                ('message', models.TextField(help_text='Enter the email message.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
