# Generated by Django 5.1.6 on 2025-02-18 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_ipaddress_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorinfos',
            name='last_visited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
