# Generated by Django 5.1.6 on 2025-02-20 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_analytics_conversion_rate_analytics_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytics',
            name='conversion_rate',
        ),
        migrations.RemoveField(
            model_name='analytics',
            name='sales_contact_visits',
        ),
        migrations.RemoveField(
            model_name='analytics',
            name='total_contacts',
        ),
        migrations.RemoveField(
            model_name='analytics',
            name='total_email_templates',
        ),
        migrations.RemoveField(
            model_name='analytics',
            name='total_page_visits',
        ),
        migrations.RemoveField(
            model_name='analytics',
            name='total_users',
        ),
    ]
