# Generated by Django 5.1.6 on 2025-02-16 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sales', '0003_visitorinfos_visit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorinfos',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='visitorinfos',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
