# Generated by Django 5.1.6 on 2025-02-17 05:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_visitorinfos_content_type_visitorinfos_object_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'ContactMessage', 'verbose_name_plural': 'ContactMessages'},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'verbose_name': 'EmailTemplate', 'verbose_name_plural': 'EmailTemplates'},
        ),
        migrations.AlterModelOptions(
            name='visitorinfos',
            options={'verbose_name': 'VisitorInfo', 'verbose_name_plural': 'VisitorInfos'},
        ),
        migrations.AlterUniqueTogether(
            name='visitorinfos',
            unique_together={('user', 'session_id')},
        ),
    ]
