# Generated by Django 5.1.6 on 2025-02-20 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_analytics_conversion_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytics',
            name='last_updated',
        ),
    ]
