# Generated by Django 5.1.6 on 2025-02-19 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_eventresponsecontact_eventresponseuser_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='ip_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.ipaddress'),
        ),
        migrations.AlterField(
            model_name='eventresponsecontact',
            name='response_status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('tentative', 'Tentative'), ('no_response', 'No Response')], default='no_response', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventresponsecontact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.contactmessage'),
        ),
        migrations.AlterField(
            model_name='eventresponseuser',
            name='response_status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('tentative', 'Tentative'), ('no_response', 'No Response')], default='no_response', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventresponseuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visitorinfos',
            name='ip_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.ipaddress'),
        ),
        migrations.AlterField(
            model_name='visitorinfos',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
