# Generated by Django 5.1.6 on 2025-02-17 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_emailtracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtracking',
            name='email_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_emails', to='sales.emailtemplate'),
        ),
        migrations.AlterField(
            model_name='emailtracking',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_emails', to=settings.AUTH_USER_MODEL),
        ),
    ]
