# Generated by Django 5.1.6 on 2025-02-19 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sales', '0007_alter_contactmessage_ip_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventresponseuser',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventresponseuser',
            name='user',
        ),
        migrations.CreateModel(
            name='EventResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('response_status', models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('tentative', 'Tentative'), ('no_response', 'No Response')], default='no_response', max_length=20)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='sales.googlecalendarevent')),
            ],
        ),
        migrations.DeleteModel(
            name='EventResponseContact',
        ),
        migrations.DeleteModel(
            name='EventResponseUser',
        ),
    ]
